on: push
jobs:
 Requests:
     name: Request1
     runs-on: self-hosted
     steps:
        - uses: actions/checkout@v2
        - name: Run sh file
          id: a
          continue-on-error: true
          
          run: |
             chmod +x Script1.sh
             ./Script1.sh $token 
            
          env:
            token: 29f238df-7432-49c0-86ff-a92b11a113ea
          
        - name: new run
          run: |
            echo "${{ steps.a.outputs.sastScan }}"
            
        - name: SAST-scan
          if: ${{ steps.a.outputs.sastScan  == 'true' }} #if
          uses: AppThreat/sast-scan-action@v1.0.0
          with:
           type: java
           
        - name: SCA-scan
          if: ${{ steps.a.outputs.scatScan  == 'true' }}
          run: echo "Perform SCAscan"
          
        - name: DAST-scan
          if:  ${{ steps.a.outputs.dastScan  == 'true' }}
          run: echo "Perform DASTscan"
          #if
            
          
            
 #Build:
 #     name: Build
  #    runs-on: ubuntu-latest
   #   steps:
    #   - name: SAST-scan
      #    if: ${{ steps.a.outputs.nikhar }} == 'true'
        #  run: echo "Nicely executing"
       #   uses: AppThreat/sast-scan-action@1.0.2
      #    with:
        #   output: sast-reports
        #   type: java
           
       # - name: SAST scan report
       #   if: always()
       #   uses: actions/upload-artifact@v1.0.0
       #   with:
       #   name: sast-reports
       #    path: sast-reports   
            
       # - id: b
       #   run: |
       #    echo ::set-output name=result::value
        #   echo 
     #   - if: a.result == 'value'             
 
      
      
      
      
      
      
    
