on: push
jobs:
  Requests:
     name: Request1
     runs-on: self-hosted
     steps:
        - uses: actions/checkout@v2
        - name: Run sh file
          id: a
          continue-on-error: true
          
          run: |
             chmod +x Script1.sh
             ./Script1.sh $token 
            
          env:
            token: 29f238df-7432-49c0-86ff-a92b11a113ea
          
        - name: new run
          run: |
            echo "heyy"
            echo "${{ steps.a.outputs.nikhar }}"
            
       # - id: b
       #   run: |
       #    echo ::set-output name=result::value
        #   echo 
     #   - if: a.result == 'value'             
 
      
      
      
      
      
      
    
